server:
  port: ${PORT:${SERVER_PORT:0}}
idRandom: ${random.value}
spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    host: localhost              # Dirección del servidor RabbitMQ
    port: 5672                   # Puerto del servidor RabbitMQ (por defecto es 5672)
    username: guest              # Nombre de usuario de RabbitMQ
    password: guest              # Contraseña de RabbitMQ
    virtual-host: /    
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents, health, info, ratelimiters, metrics

  health:
    circuitbreakers:
      enabled: true

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true
    configs:
      default:
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      movies:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - feign.FeignException$InternalServerError
