# Configuración del Servidor y Spring
server:
  port: ${PORT:${SERVER_PORT:0}}
idRandom: ${random.value}

spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

# Configuración de Cola (Queue)
queue:
  persona:
    name: practicaQueue

# Configuración de Eureka
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Configuración de Actuadores y Salud (Management)
management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers, circuitbreakerevents, health, info, ratelimiters, metrics

  health:
    circuitbreakers:
      enabled: true

  endpoint:
    health:
      show-details: always

# Configuración de Resilience4j (Circuit Breaker y Retry)
resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        registerHealthIndicator: true
    configs:
      default:
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      movies:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - feign.FeignException$InternalServerError
