server:
  port: ${PORT:${SERVER_PORT:0}}
idRandom: ${random.value}
spring:
  application:
    name: movie-service
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    host: localhost              # Dirección del servidor RabbitMQ
    port: 5672                   # Puerto del servidor RabbitMQ (por defecto es 5672)
    username: guest              # Nombre de usuario de RabbitMQ
    password: guest              # Contraseña de RabbitMQ
    virtual-host: /    
  queue:
    persona:
      name: practicaQueue
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev
    username: root
    password: 123456789
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
